# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Cassidy
email: johnpatrickcassidy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnpatrickcassidy.com" # the base hostname & protocol for your site
twitter_username: JohnPCassidy
github_username:  johnpatrickcassidy

# Build settings
markdown: kramdown

#By default, Jekyll copies all folders in the source that don’t have a leading underscore, so it will copy over the node_modules directory to your _site build folder. To avoid this, exclude node_modules from processing by adding exclude: ['node_modules'] to your _config.yml file.
exclude: ['node_modules', ‘css’, ‘_scss’]

# tell Jekyll not to erase the CSS directory in the _site output folder each time it rebuilds by adding this to _config.yml
keep_files: ['_site/css']

permalink: /:categories/:title.html